language: node_js
node_js:
  - 10.16.2
addons:
  chrome: stable
  ssh_known_hosts: $UPLOAD_SERVER

before_script:
  - echo "$UPLOAD_SERVER ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBH2TydShl6oPEvF+2gWsCYLbfgps6rpZjbPz889LsWUvZiLnvoQUlmH8C4i1cUAl+eq5CiP7egcbrJ60p7fvM/k=" >> $HOME/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_d0f036b99c7e_key -iv $encrypted_d0f036b99c7e_iv -in ci/id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
cache: npm
jobs:
  include:
    - stage: test
      script:
        - npm run pretest
        - npx serve -n -l 5000 example/public &
        - sleep 5
        - SERVER_PID=$!
        - npm run test
        - kill $SERVER_PID
        - ls -l *.png
        - rsync -avz -e'ssh -v -i /tmp/id_rsa' *.png ci_upload@$UPLOAD_SERVER:/tmp
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx xsemantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
