jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: --delete--
        cleanup: "false"
        script:
          - npx semantic-release
