language: node_js
node_js:
  - 10.16.2
cache: npm
script:
  - npx serve -n -l 5000 example/public &
  - SERVER_PID=$!
  - npm run test
  - kill $SERVER_PID
jobs:
  include:
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
