language: node_js
addons:
  chrome: stable
  ssh_known_hosts: $UPLOAD_SERVER
env:
  - BROWSER=chrome
jobs:
  include:
    - stage: test
      script:
        - npm run test
        - 'mkdir -p "${TRAVIS_REPO_SLUG}/${TRAVIS_JOB_ID}"'
        - 'mv test-results "${TRAVIS_REPO_SLUG}/${TRAVIS_JOB_ID}"'
        - >-
          rsync -av "${TRAVIS_REPO_SLUG}/${TRAVIS_JOB_ID}"
          ci-upload@$UPLOAD_SERVER:/somewhere
      node_js:
        - lts/*
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        script:
          - npx semantic-release
        cleanup: 'false'
before_script:
  - >-
    echo "$UPLOAD_SERVER ecdsa-sha2-nistp256
    AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBH2TydShl6oPEvF+2gWsCYLbfgps6rpZjbPz889LsWUvZiLnvoQUlmH8C4i1cUAl+eq5CiP7egcbrJ60p7fvM/k="
    >> $HOME/.ssh/known_hosts
  - >-
    openssl aes-256-cbc -K $encrypted_d0f036b99c7e_key -iv
    $encrypted_d0f036b99c7e_iv -in ci/id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
branches:
  only:
    - master
    - development
    - /^greenkeeper/.*$/
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
