name: CI
'on': push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16.12.0
          - 18.4.0
        browser:
          - chrome
          - firefox
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm install
      - run: npm test
        env:
          BROWSER: ${{ matrix.browser }}
      - run: npm run cover --if-present
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage/lcov.info
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/build/test/**/*
          retention-days: 3
          name: screenshots
        if: always()
      - run: npm cit
        env:
          BROWSER: ${{ matrix.browser }}
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 18.4.0
          cache: npm
      - run: npm install
      - run: npx semantic-release
        env:
          CI: 'true'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKGBUILD_PUBLISH: ${{ secrets.PKGBUILD_PUBLISH }}
      - name: Dependencies
        run: >
          sudo apt-get update

          sudo apt-get install ksh curl

          wget
          https://github.com/ThePoorPilot/pacman-utils/releases/download/5.2.2-3_2.31-0/pacman-utils_5.2.2-3_amd64.deb

          sudo apt-get install -f ./pacman-utils_5.2.2-3_amd64.deb
      - run: npm ci
